//d require('./test/count-cats.test');
//d require('./test/carbon-dating.test');
//d require('./test/dream-team.test');
//d require('./test/extended-repeater.test');
//d require('./test/what-season.test');
//d require('./test/vigenere-cipher.test');
require('./test/hanoi-tower.test');
//d require('./test/transform-array.test');
//d require('./test/simple-chain.test');
//d require('./test/recursive-depth.test');